name: KRAL

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 99999999

    steps:
    - name: 1. Ngrok İndiriliyor!
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Emre37destan/KralVDS/main/Files/nssm.exe -OutFile nssm.exe
    - name: 2. Ngrok Arşivden Çıkarılıyor!
      run: Expand-Archive ngrok.zip
    - name: 3. Token İşleniyor!
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: 4. Önemli Dosyaları İndiriliyor!
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Emre37destan/KralVDS/main/Files/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Emre37destan/KralVDS/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Emre37destan/KralVDS/main/Files/loop.bat -OutFile loop.bat
    - name: 5. TS Etkinleştiriliyor!
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: 6. RDP için Güvenlik Duvarı Aktif!
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: 7. Regdit'ten RDP Mülküne İzin Veriliyor!
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: 8. Tünel Oluşturuluyor!
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: 9. Zaman Aşımı Komut Dosyasını İndiriliyor!
      run: cmd /c NGROK-CHECK.bat
    - name: 10. Max 6 Saat Açık
      run: cmd /c loop.bat
      
